geeckshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('register/', authapp.register, name='register'),
    path('login/', authapp.login, name='login'),
    path('edit/<int:pk>/', authapp.EditView.as_view(), name='edit'),
    path('logout/', authapp.logout, name='logout'),
]

geeckshop/geeckshop/urls.py
from django.contrib import admin
from django.urls import path, include
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', mainapp.products, name='products'),
    path('contact/', mainapp.contacts, name='contacts'),
    path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls', namespace='auth')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geeckshop/authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class ShopUser(AbstractUser):
    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'

    avatar = models.ImageField(upload_to='users_avatars', blank=True)
    age = models.PositiveIntegerField(verbose_name='возраст')

    def __str__(self):
        return self.username

geeckshop/authapp/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import forms

from .models import ShopUser


class ShopUserRegisterForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'password1', 'password2', 'email', 'age', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Вы слишком молоды!")

        return data

geeckshop/authapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.views.generic.edit import UpdateView
from django.contrib import auth
from django.urls import reverse, reverse_lazy
from .forms import ShopUserRegisterForm
from .models import ShopUser


def register(request):

    if request.method == 'POST':
        register_form = ShopUserRegisterForm(request.POST, request.FILES)
        if register_form.is_valid():
            user = register_form.save()
            auth.login(request, user)
            return HttpResponseRedirect(reverse('main'))
    else:
        register_form = ShopUserRegisterForm()

    context = {
        'form': register_form,
        'title': 'Register',
        'submit_label': 'Zergistrirovatsya'
    }
    return render(request, 'authapp/register.html', context)


def login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        next = request.POST.get('next')
        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            if next:
                return HttpResponseRedirect(next)
            else:
                return HttpResponseRedirect(reverse('main'))

    return render(request, 'authapp/login.html', {'title': 'Enter', 'next': request.GET.get('next')})


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main'))


class EditView(UpdateView):
    model = ShopUser
    template_name = 'authapp/register.html'
    fields = 'username', 'email', 'avatar'
    success_url = reverse_lazy('main')

    def get_context_data(self, **kwargs):
        context = super(EditView, self).get_context_data(**kwargs)
        context['title'] = 'Redaktirovat profile'
        context['submit_label'] = 'Primenit'
        return context

geeckshop/authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>
        {{ title|title }}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    {% endblock %}
<body>
	<div class="container">
        <div class="login">
            <a href="{% url "main" %}">На главную</a>
            <br>
            {% block content %}

            {% endblock %}
</body>
</html>

geeckshop/authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}

{% block content %}
    <form class="form-horizontal" action='{% url "auth:login" %}' method="POST">
        {% csrf_token %}
        <input class="form-control" name="username" placeholder="Imya polzovatelya"><br>
        <input class="form-control" name="password" type="password" placeholder="Parol"><br>
        {% if next %}
            <input type="hidden" name="next" value={{ next }}>
        {% endif %}
        <input class="form-control" type="submit" value="Enter">
    </form>
{% endblock %}

geeckshop/authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}

{% block content %}
    <form class="form-horizontal" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="form-control" type="submit" value="Send">
    </form>

{% endblock %}