geeckshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('register/', authapp.register, name='register'),
    path('login/', authapp.login, name='login'),
    path('edit/<int:pk>/', authapp.EditView.as_view(), name='edit'),
    path('logout/', authapp.logout, name='logout'),
]

geeckshop/basketapp/urls.py
from django.urls import path

from .views import add, remove, basket, edit

app_name = 'basketapp'

urlpatterns = [
    path('', basket, name='read'),
    path('add/<int:product_pk>/', add, name='add'),
    path('remove/<int:product_pk>', remove, name='remove'),
    path('edit/<int:pk>/', edit, name='edit'),
]

geeckshop/geeckshop/urls.py
from django.contrib import admin
from django.urls import path, include
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', mainapp.products, name='products'),
    path('contact/', mainapp.contacts, name='contacts'),
    path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls', namespace='auth')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geeckshop/mainapp/urls.py
from django.urls import path

from mainapp.views import products

app_name = 'mainapp'

urlpatterns = [
    path('', products, name='index'),
    path('category/<int:pk>/', products, name='category'),
]

geeckshop/mainapp/models.py
from django.db import models
class ProductCategory(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    name = models.CharField(verbose_name='imya categorii', max_length=64, unique=True)
    desc = models.TextField(verbose_name='opisanie categorii', blank=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='imya producta', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='kratko', max_length=60, blank=True)
    description = models.TextField(verbose_name='podrobno', blank=True)
    price = models.DecimalField(verbose_name='cena', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='sklad', default=0)
    is_hot = models.BooleanField(verbose_name='goryachi product', default=False)

    def __str__(self):
        return "{} ({})".format(self.name, self.category.name)

geeckshop/mainapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product, ProductCategory


def main(request):
    context = {'username': 'alexey'}
    return render(request, 'mainapp/main.html', context)


def products(request, pk=None):
    products = Product.objects.all()

    if pk or pk == 0:
        if pk != 0:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = products.filter(category=category)
        context = {'products': products, 'categories': ProductCategory.objects.all()}
        return render(request, 'mainapp/products.html', context)
    else:
        hot_product = Product.objects.filter(is_hot=True).first()
        context = {'hot_product': hot_product, 'categories': ProductCategory.objects.all()}
        return render(request, 'mainapp/hot_product.html', context)


def contacts(request):
    return render(request, 'mainapp/contacts.html')

geeckshop/mainapp/templates/mainapp/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{{ title }} </title>

    {% block css %}
    {% endblock %}
</head>

<body>
{% include 'mainapp/includes/inc_menu.html' %}
{% block body %}
{% endblock %}
{% block js %}
{% endblock %}
</body>
</html>

geeckshop/mainapp/templates/mainapp/contacts.html
{% extends 'mainapp/base.html' %}


{% block body %}
    <h1> Kontakti </h1>
{% endblock %}

geeckshop/mainapp/templates/mainapp/main.html
{% extends 'mainapp/base.html' %}
{%load static %}


{% block css %}
    <link rel="stylesheet" type="text/css" href={% static 'css/style.css' %}>
{% endblock %}

{% block body %}
    <h1> Glavnaya </h1>
    {% if request.user.is_authenticated %}
        <div>Privet, {{ request.user.username|title}}!</div>
    {% else %}
        <div>Privet!</div>
    {% endif %}
{% endblock %}

geeckshop/mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load custom_tags %}

{% block title %}
    <title>Продукты</title>
{% endblock %}

{% block content %}
    <h1>Products</h1><br>
    <div>Kolichestvo produktov v korzine: {{ request.user|basket_total_quantity }}</div>
    <div>Obshaya stoimost: {{ request.user|basket_total_cost }} руб.</div>
    <h3>Categories</h3>
    {% include 'mainapp/includes/inc_category_menu.html' %}
    <br><br>
    <div style="display: flex; flex-wrap: wrap;" class="category-products clearfix">
        {% for product in products %}
            <div style="margin: 20px" class="block">
                  <div class="card" style="width: 18rem;">
                      <img src="/media/{{ product.image }}" class="card-img-top" alt="product">
                      <div class="card-body">
                          <h5 class="card-title">{{ product.name }}</h5>
                          <p class="card-text">{{ product.short_desc }}</p>
                          <a href="{% url 'basket:add' product.pk %}">Dobavit v korziny</a>
                          <br>
                          <a href="{% url 'basket:remove' product.pk %}">Ydalit iz korzini</a>
                      </div>
                  </div>
              </div>
        {% endfor %}
    </div>
{% endblock %}